private_gsheets_url = "https://docs.google.com/spreadsheets/d/1pNlChcOvhuFRCG_iAETraJRf0s1M4uMpaX6J1uNRqpg/edit?usp=sharing"

[gcp_service_account]
type= ""
project_id= ""
private_key_id= ""
private_key= ""
client_email= ""
client_id= ""
auth_uri= ""
token_uri= ""
auth_provider_x509_cert_url= ""
client_x509_cert_url= ""